name: Generate Karaoke ASS

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'How to provide song and lyrics'
        type: choice
        options:
        - Use files committed to the repository
        - Provide audio URL and paste lyrics (no commit needed)
        default: Use files committed to the repository
      audio_file:
        description: 'Audio file name in repo (e.g. audio[vocals].mp3)'
        default: song.mp3
      lyrics_file:
        description: 'Lyrics file in repo'
        default: lyrics.txt
      audio_url:
        description: 'Direct download URL to audio (for no-commit mode)'
        required: false
      lyrics_text:
        description: 'Paste full lyrics here (one line per subtitle line)'
        type: string
        required: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && apt install -y unzip wget ffmpeg jq

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          pip install faster-whisper==1.0.3 demucs torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Download working aegisub-cli (v0.6.0 – last Linux build, works forever)
        run: |
          wget -O aegisub-cli.zip https://github.com/Myaamori/aegisub-cli/releases/download/v0.6.0/aegisub-cli-linux-x64.zip
          unzip -o aegisub-cli.zip
          chmod +x aegisub-cli-linux-x64
          ./aegisub-cli-linux-x64 --version || true  # shows version

      - name: Prepare audio & lyrics
        run: |
          if [ "${{ inputs.mode }}" = "Provide audio URL and paste lyrics (no commit needed)" ]; then
            wget -O input_audio "${{ inputs.audio_url }}"
            echo '${{ inputs.lyrics_text }}' > lyrics.txt
          else
            cp "${{ inputs.audio_file }}" input_audio
            cp "${{ inputs.lyrics_file }}" lyrics.txt
          fi
          ffmpeg -y -i input_audio -ar 16000 -ac 1 -vn vocals_raw.wav

      - name: Isolate vocals with Demucs
        run: |
          python -m demucs.separate --two-stems=vocals -n htdemucs --jobs=4 vocals_raw.wav
          mv separated/htdemucs/vocals_raw/vocals.wav vocals.wav

      - name: Generate pre-template .ass
        run: python generate_ass.py

      - name: Apply Karaoke Templater effects
        run: |
          ./aegisub-cli-linux-x64 pre.ass final.ass "Karaoke Templater"
          cat final.ass | head -n 30  # debug: show it worked

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: karaoke-ass
          path: final.ass
